{% set version = "2024.0.1" %}
{% set version_major_minor = ".".join(version.split('.')[:2]) %}

package:
  name: hugin-base
  version: {{ version }}

source:
  # url: https://iweb.dl.sourceforge.net/project/hugin/hugin/hugin-{{ version_major_minor }}/hugin-{{ version }}.tar.bz2
  url: https://sourceforge.net/projects/hugin/files/hugin/hugin-{{ version_major_minor }}/hugin-{{ version }}.tar.bz2
  sha256: 13ec0cdeeb4eb63149c833768d3e374e7cf5a6a8d8d02d50885ce496f05ba7e4
  patches:
    - hugin-openexr3.patch
    # Line endings frustrate me. So I've just vendored the files but documented the patch.
    # - windows_unbundle.patch
    # - windows_unified_manifest.patch
    - link_to_shared_getopt_win.patch
    # finite keyword deprecated in C99
    - isfinite.patch
    # My own patch following
    # https://github.com/flann-lib/flann/commit/be80cefa69b314a3d9e1ab971715e84145863ebb#diff-6c163d1ce608acc3d5252db5576dd1673326ec02dbaae54b695a7b19c9223a0dR271
    - avoid_random_shuffler_for_cpp17.patch

build:
  number: 2

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - gettext
    - cmake
    - libgomp      # [linux]
    - make         # [unix]
    - ninja        # [win]
    - binutils     # [linux]
    - pkg-config   # [unix]
  host:
    - xorg-libxfixes           # [linux]
    - xorg-libsm               # [linux]
    - libgl-devel              # [linux]
    - libegl-devel             # [linux]
    - pango
    - pip
    - setuptools
    - libtiff
    - libpano13
    - libjpeg-turbo
    - libpng
    - imath
    - zlib
    - openexr
    - libvigra
    - exiv2
    - expat
    - glew
    - libsqlite
    - lcms2
    - perl
    - libboost-devel
    - fftw
    - libglu           # [linux]
    # For some reason these are requried by the windows
    # build system
    - enblend
    - pthreads-win32  # [win]
    - getopt-win32    # [win]
  run:
    - pthreads-win32  # [win]
    # not sure why run exports isn't working
    - exiftool
    - enblend
    - xorg-libx11  # [linux]
    - xorg-libsm   # [linux]

test:
  commands:
    - nona -help
    - cpfind -help
    - autooptimiser -help
    - pano_modify -help

outputs:
  - name: hugin-base
    script: build_base.sh  # [unix]
    script: bld_base.bat  # [win]

  - name: hugin
    build:
      skip: true  # [osx]
      ignore_run_exports_from:
        - libboost-devel
    script: build_gui.sh  # [unix]
    script: bld_gui.bat  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
        - gettext
        - libgomp      # [linux]
        - make   # [unix]
        - ninja  # [win]
        - cmake
        - binutils  # [linux]
        - pkg-config  # [unix]
      host:
        - {{ pin_subpackage('hugin-base', exact=True) }}
        - xorg-libxfixes           # [linux]
        - xorg-libsm               # [linux]
        - libgl-devel              # [linux]
        - libegl-devel             # [linux]
        - pango
        - pip
        - libtiff
        - libpano13
        - libjpeg-turbo
        - libpng
        - imath
        - zlib
        - openexr
        - libvigra
        - exiv2
        - expat
        - glew
        - libsqlite
        - lcms2
        - perl
        # build complains on windows if we don't have the libs, as it's in the link interface of hugin-base;
        # no selector because we also ignore run-export everywhere
        - libboost-devel
        - fftw
        - libglu           # [linux]
        # For some reason these are requried by the windows
        # build system
        - enblend
        - pthreads-win32  # [win]
        - getopt-win32    # [win]
        - wxwidgets
        - libglu  # [linux]
      run:
        - {{ pin_subpackage('hugin-base', exact=True) }}

about:
  home: http://hugin.sourceforge.net/
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING.txt
  summary: Panorama photo stitcher

  description: |
    An easy to use cross-platform panoramic imaging toolchain based on Panorama Tools.

    With Hugin you can assemble a mosaic of photographs into a complete
    immersive panorama, stitch any series of overlapping pictures and much
    more.

  doc_url: http://hugin.sourceforge.net/docs/
  dev_url: https://sourceforge.net/projects/hugin/

extra:
  recipe-maintainers:
    - hmaarrfk
